# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김민겸
title: 삽질 전문가
email: alsrua7222@naver.com
website: https://blog.naver.com/alsrua7222

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: alsrua7222
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://blog.naver.com/alsrua7222
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Python & C++ 기반으로 ERP 시스템, 사무 자동화, 데이터 파이프라인 구축 경험
  Node & Typescript / Python / React 기반으로 웹 구축 및 AWS Serverless 구축 경험
  Java & Kotlin (Android) 기반으로 안드로이드 어플리케이션 배포 경험
  
  현재 <mark>정보관리기술사</mark> 자격증을 현재 목표로 공부하고 있는 취업준비생 입니다.

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    quote: >
      학교, 개인, 외주 프로젝트에 사용 중 혹은 사용했던 기술들입니다.
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Python, Go
          - Java, Nodejs(ts), Spring, Spring Boot
          - Firebase Hosting, Firebase Storage, AWS Lambda, AWS S3
          - Gradle, Maven, pip & npm(Server Side)
          - VS Code, IntelliJ
          
      - layout: left
        title: Frontend
        description: | # this will include new lines to allow paragraphs
          - Python, React, ES6
          - pip & npm(Client Side)
          
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - Python, C++
          - MySQL, MariaDB, NoSQL, PostgreSQL
          - Firebase Analysis, Google Analysis, AWS SQS, AWS SNS
          - Apache, Nginx
          - Visual Studio
          
      - layout: left
        title: Android
        description: | # this will include new lines to allow paragraphs
          - Java(Kotlin), React-Native
          - SQLite
          - Appium, ADB Shell
          - AndroidStudio, VS Code, Amulator
          
      - layout: left
        title: Big-Data
        description: | # this will include new lines to allow paragraphs
          - Python, R
          - PlotMap, Pandas, ggplot2
          - PyTorch, scikit-learn, tensorflow, keras
          - Google Colab, Jupyter Notebook

  - title: Opensource
    layout: list
    content: | # this will include new lines to allow paragraphs
      - layout: left
        title: 개인 블로그
        sub_title: https://blog.naver.com/alsrua7222
        
      

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 경남대학교
        caption: 2018 - 2022
        sub_title: 컴퓨터공학부 소프트웨어
        description: | # this will include new lines to allow paragraphs
          - 1학년(2018년)
            - 3.9 / 4.5 평점
            - V.O.S 동아리 멘티(6개월) & 멘토(6개월)
            - 개인자원봉사(32시간)
          - 2학년(2019년)
            - 4.0 / 4.5 평점
            - V.O.S 동아리 멘토(1년)
            - 경남본부 Infra개발 단기 체험형, 우체국 우정사업본부 단기 아르바이트
            - 소프트웨어 교육지도사 취득(9월)
            - 개인자원봉사(32시간)
          - 3학년(2020년)
            - 4.3 / 4.5 평점
            - V.O.S 동아리 멘토(9개월 / 20년 10월까지 활동)
          - 4학년(2021년)
            - 4.3 / 4.5 평점
            - 운전면허1종 취득(1월)
            - 정보처리기사 취득(6월)
            - 졸업작품 심사 통과 후, 졸업 자격 취득(7월)
            - 취직 활동 시작(9월)
            - 외주 프로젝트 시작(12월)
          - 졸업(2022년 2월)
            - 총 4.08 / 4.5 평점
              - 전체 130학점
            - 총 4.16 / 4.5 평점
              - 전공 82학점
            - 3등 우수 졸업
      - layout: left
        title: 창원경일고등학교
        caption: 2015 - 2018
        description: | # this will include new lines to allow paragraphs
          - 1학년(2015년)
            - 평균등급 8등급
            - 정보화(C, 컴퓨터개론) 교육 독학
          - 2학년(2016년)
            - 평균등급 6등급
            - 정보화(리버싱 엔지니어링, C++, 컴퓨터구조) 교육 독학
            - 그레이 해커 활동
          - 3학년(2017년)
            - 평균등급 3등급
          - 졸업(2018년 2월)
            - 출결사항
              - 1학년 개근상
              - 2학년 개근상
              - 3학년 결석 - 질병 1건
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
