# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김민겸
title: 삽질 전문가
email: alsrua7222@naver.com
website: https://blog.naver.com/alsrua7222

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: alsrua7222

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://blog.naver.com/alsrua7222

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Python & C++ & Nodejs로 학교, 개인, 외주 프로젝트를 개발해 왔습니다.   
  스스로 이룬 성과보다 <mark>팀이 기뻐하거나 만족하는 성과</mark>에 재미들려 자동화, CI/CD, AWS 아키텍처, 클린 코드, 배포 등 학교에서 접해보지 못한 경험들을 만들어 제공하기도 했습니다.   
  다양한 경험 활동, 성장 활동을 하여 준비하고 취직준비하는 개발자입니다.
  
  현재 모든 분야에서 유연하게 대응 잘하고 싶어 <mark>정보관리기술사 자격증 취득</mark>를 현재 목표로 공부하고 있습니다.

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    quote: >
      학교, 개인, 외주 프로젝트에 사용 중 혹은 사용했던 기술들입니다.
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Python, Go
          - Java, Nodejs(ts), Spring, Spring Boot
          - Firebase Hosting, Firebase Storage, AWS Lambda, AWS S3
          - Gradle, Maven, pip & npm(Server Side)
          - VS Code, IntelliJ
          
      - layout: left
        title: Frontend
        description: | # this will include new lines to allow paragraphs
          - Python, C#, React, ES6
          - .Net, NuGet, pip & npm(Client Side)
          
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - Python, C++
          - MySQL, MariaDB, NoSQL, PostgreSQL
          - Firebase Analysis, Google Analysis, AWS SQS, AWS SNS
          - Jenkins, AWS CD
          - Apache, Nginx
          - Visual Studio
          
      - layout: left
        title: Android
        description: | # this will include new lines to allow paragraphs
          - Java(Kotlin), React-Native
          - SQLite
          - Appium, ADB Shell
          - AndroidStudio, VS Code, Amulator
          
      - layout: left
        title: Big-Data
        description: | # this will include new lines to allow paragraphs
          - Python, R
          - PlotMap, Pandas, ggplot2
          - PyTorch, scikit-learn, tensorflow, keras
          - Google Colab, Jupyter Notebook

  - title: Opensource
    layout: list
    content: | # this will include new lines to allow paragraphs
      - layout: left
        title: 개인 블로그
        sub_title: https://blog.naver.com/alsrua7222
        description: | # this will include new lines to allow paragraphs
          - 개발 진행하면서 생긴 문제점, 사용한 기술, 실수한 점, 일상에 대해서 자세히 정리하여 공유하기 위해 개설한 블로그
      - layout: left
        title: SeleniumNaverCafeWrite
        sub_title: https://github.com/alsrua7222/SeleniumNaverCafeWrite
        description: | # this will include new lines to allow paragraphs
          - 네이버 API 중 글쓰기 API 지원 중단으로인해 만들어진 카페 글쓰기 API 대체제.
          - Python 코드로 원하는 내용을 작성하여 자동으로 글쓰기 할 수 있음.
      - layout: left
        title: NaverKinFilter
        sub_title: https://github.com/alsrua7222/NaverKinFilter
        description: | # this will include new lines to allow paragraphs
          - 네이버 지식인에서 이상한 사람들을 자체적으로 판단하고 거르는 일이 귀찮아서 만든 크롬 확장프로그램.
          - 이벤트 리스너를 통해 임의로 설정한 조건에 의해 필터링.
          - 현재 크롬 확장프로그램 Shop에서 찾아서 설치할 수 있음.
      - layout: left
        title: CaptchaSolveKit(예정)
        sub_title: None
        description: | # this will include new lines to allow paragraphs
          - 자동화 수행하면서 생기는 캡챠 인식 문제를 해결하는 프로그램.
          - 각 사이트에 탑재된 캡챠 문제지에 대한 해결해줌.
          - <mark>CRNN</mark> 모델을 사용함.
          - 이미지 정보를 최대한 유지한 채, <mark>ResNet</mark> 신경망 구조를 사용함.
          - 정확도 99.89%으로 유의미한 결과를 얻는데에 성공.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 경남대학교
        caption: 2018 - 2022
        sub_title: 컴퓨터공학부 소프트웨어
        description: | # this will include new lines to allow paragraphs
          - 1학년(2018년)
            - 3.9 / 4.5 평점
            - V.O.S 동아리 멘티(6개월) & 멘토(6개월)
            - 개인자원봉사(32시간)
          - 2학년(2019년)
            - 4.0 / 4.5 평점
            - V.O.S 동아리 멘토(1년)
            - 경남본부 Infra개발 단기 체험형, 우체국 우정사업본부 단기 아르바이트
            - 소프트웨어 교육지도사 취득(9월)
            - 개인자원봉사(32시간)
          - 3학년(2020년)
            - 4.3 / 4.5 평점
            - V.O.S 동아리 멘토(9개월 / 20년 10월까지 활동)
          - 4학년(2021년)
            - 4.3 / 4.5 평점
            - 운전면허1종보통 취득(1월)
            - 정보처리기사 취득(6월)
            - 졸업작품 심사 통과 후, 졸업 자격 취득(7월)
            - 취직 활동 시작(9월)
            - 외주 프로젝트 시작(12월)
          - 졸업(2022년 2월)
            - 총 4.08 / 4.5 평점
              - 전체 130학점
            - 총 4.16 / 4.5 평점
              - 전공 82학점
            - 3등 우수 졸업
      - layout: left
        title: 창원경일고등학교
        caption: 2015 - 2018
        description: | # this will include new lines to allow paragraphs
          - 1학년(2015년)
            - 평균등급 8등급
            - 정보화(C, 컴퓨터개론) 교육 독학
          - 2학년(2016년)
            - 평균등급 6등급
            - 정보화(리버싱 엔지니어링, C++, 컴퓨터구조) 교육 독학
            - 그레이 해커 활동
          - 3학년(2017년)
            - 평균등급 3등급
          - 졸업(2018년 2월)
            - 출결사항
              - 1학년 개근상
              - 2학년 개근상
              - 3학년 결석 - 질병 1건
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
